app = "emotion-detection-v2"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5001"
  PYTHON_VERSION = "3.10.12"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  strategy = "immediate"
  release_command = "python -m pip install -r requirements.txt"

[processes]
  app = "python app.py"